### ISSUE TITLE
Typo and API key shown in notebook

### ISSUE THREAD

**Issue by utf** [hackingmaterials/matminer_examples#40]
I've noticed a couple of typos and other minor bugs in the basic data retrieval notebook. I will keep track of them in this issue and submit a pull request containing fixes when I've run through all the notebook examples.

In `data_retrieval_basics.ipynb`:

- The order of cell execution is non-linear (so the numbers at the side of the cells are not incremental). This isn't necessarily a problem but may be confusing for people new to notebooks.
- Under the Materials Project heading, example 2: `df.to_cv(...)` should be `df.to_csv(...)`
- Under Citrine informatics: an API key is given when initializing the `CitrineDataRetrieval`. This should be removed.
- Capitalise Globus
- Empty cell at end of notebook

*(I'll edit this message if I find anything else)*

**Comment by ardunn** [comment]
Whoops, these are from when @albalu and I did the MP workshop and forgot to change things back. 

@albalu your API key is showing!

**Comment by albalu** [comment]
That was public information the moment we put it up in the git log, I tried to change my key after the workshop but it seemed like Citrine didn't have this option. Thanks @utf  for noticing these.

**Comment by computron** [comment]
@utf can you go ahead and issue some PRs to fix?

I'm not really so concerned about the key being in the log, let's just get it off the live example
