### ISSUE TITLE
Binder examples cannot be run interactively

### ISSUE THREAD

**Issue by utf** [hackingmaterials/matminer_examples#41]
When running the notebooks in binder (as per the documentation), the lack of API keys mean the notebooks cannot be run interactively. Another issue is that matminer is not installed using the optional dependencies, so the MPDS examples fail with another error message.

Possible solutions:
- Set the proper environment variables in binder. I don't know if this can be done without the keys being public in anyway.
- Remove the link to binder as the notebooks can be viewed in the GitHub repository, just not run interactively.

If binder provides other benefits further to running the notebooks interactively then I guess it could make sense to leave the link in the documentation.

**Comment by computron** [comment]
Would it be possible to get the binder links to run by adding matminer as an optional-dep and also requiring the user to edit their API keys? e.g. there is a cell that looks like this:

```
# Enter your API key below!
API_KEY = None
if not API_KEY:
    raise ValueError("You need to modify this notebook and enter your API key above!!")
```

Then when running the binder notebook it will be clear to everyone that they need to enter their API key to proceed.
