### ISSUE TITLE
update examples to use new seaborn-style data set loaders

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer_examples#44]
Probably for @Doppe1g4nger

**Comment by Doppe1g4nger** [comment]
Addressed in #45

**Comment by utf** [comment]
This can be closed now?

**Comment by computron** [comment]
@utf feel free to close an issue if you're pretty confident it's done

**Comment by utf** [comment]
I can't close issues on here or matminer!

**Comment by computron** [comment]
I added you as an admin, let me know if you have problems being admin to any of our codes
