### ISSUE TITLE
error: "NameError: name 'staticmethodzoom' is not defined"

### ISSUE THREAD

**Issue by nitin0301** [hackingmaterials/matminer_examples#51]
I am using the Anaconda environment and the Ipython notebook. 

When using: 
from matminer.featurizers.composition import ElementProperty

I get following error:

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-14-2cb29ab0ed28> in <module>
----> 1 from matminer.featurizers.composition import ElementProperty

~/anaconda/envs/py3/lib/python3.6/site-packages/matminer/featurizers/composition.py in <module>
     16 
     17 from matminer.featurizers.base import BaseFeaturizer
---> 18 from matminer.featurizers.utils.stats import PropertyStats
     19 from matminer.utils.data import DemlData, MagpieData, PymatgenData, \
     20     CohesiveEnergyData, MixingEnthalpy, MatscholarElementData

~/anaconda/envs/py3/lib/python3.6/site-packages/matminer/featurizers/utils/stats.py in <module>
     13 
     14 
---> 15 class PropertyStats(object):
     16     """This class contains statistical operations that are commonly employed
     17     when computing features.

~/anaconda/envs/py3/lib/python3.6/site-packages/matminer/featurizers/utils/stats.py in PropertyStats()
    337         return np.array(data_lst).flatten()
    338 
--> 339     @staticmethodzoom
    340     def quantile(data_lst, weights=None, q=0.5):
    341         """

NameError: name 'staticmethodzoom' is not defined

**Comment by ardunn** [comment]
Hi @nitin0301,

Which version of matminer are you using (do `conda list`)? On the current master branch I do not see this issue (I am guessing it is just a typo):

```
@staticmethod
    def quantile(data_lst, weights=None, q=0.5):
        """
        Return a specific quantile.
        Args:
            data_lst (list or np.ndarray): 1D data list to be used for computing
                quantiles
            q (float): The quantile, as a fraction between 0 and 1.
        Returns:
            (float) The computed quantile of the data_lst.
        """
        q = float(q)
        return np.quantile(data_lst, q=q)
```

The first thing I would recommend is upgrading your matminer to the newest version.

**Comment by nitin0301** [comment]
I think it is the current version:

matminer                  0.5.2                    pypi_0    pypi

**Comment by computron** [comment]
Look like somehow the word "zoom" got added in your source code. Please make sure you didn't add it unintentionally. Anyway, you can probably just delete the "zoom" part like in @ardunn 's code example

**Comment by ardunn** [comment]
@computron it is in the matminer 0.5.2(?) release: https://pypi.org/project/matminer/#files

Seems like the only release it is in?

**Comment by computron** [comment]
Yes it looks like that release has some issues, let me try a new one now

**Comment by computron** [comment]
@nitin0301 - thanks for reporting
@ardunn  - thanks for checking this

I just pushed matminer v0.5.3 which should fix this.

**Comment by nitin0301** [comment]
Thanks @computron. Everything working after removing zoom.
