### ISSUE TITLE
There is an Inconsistency in matminer.featurizers.structure.CoulombMatrix()

### ISSUE THREAD

**Issue by abugh** [hackingmaterials/matminer_examples#56]
In featurize function, there are below coments.
""
        Get Coulomb matrix of input structure.

        Args:
            s: input Structure (or Molecule) object.

        Returns:
            m: (Nsites x Nsites matrix) Coulomb matrix.
"""
Which said that the function returns N * N matrix.

But Actually， it return an N-dimension vector, because they return the characteristic value of Coulomb Matrix.

**Comment by ardunn** [comment]
You can toggle matrix form or flattened form for CoulombMatrix
