### ISSUE TITLE
The 'Structure' object?

### ISSUE THREAD

**Issue by 1477983539** [hackingmaterials/matminer_examples#60]
Hello!How can I get the same format as the 'structure' field in the examples datasets? I only have some POSCAR files.Can someone help me?
BestWishes!

**Comment by computron** [comment]
```
from pymatgen import Structure
s = Structure.from_file("POSCAR")
```

Note - this is more a question for pymatgen, and help is through www.matsci.org

**Comment by 1477983539** [comment]
Thanks!
