### ISSUE TITLE
You must run 'fit' first!

### ISSUE THREAD

**Issue by zw1900686** [hackingmaterials/matminer_examples#64]
When I run PRDF class, I encounter this error "You must run 'fit' first!".

**Comment by ardunn** [comment]
Hi @zw1900686 

Not all of the notebooks are up to date with the newest matminer, so if you are using the newest matminer to run an older notebook, it might not work. I believe most of the notebooks have a compatible version of matminer listed at the top.

If you are running PRDF on your own data (i.e., not from a notebook) and you're still having trouble, please ask around on our forum https://matsci.org/c/matminer
