### ISSUE TITLE
No module named 'figrecipes' 

### ISSUE THREAD

**Issue by kittiphong-am** [hackingmaterials/matminer_examples#66]
Hi,

I follow the example of **matminer** with **figrecipes**.
But it error at the first import line

`from matminer.figrecipes.plot import PlotlyFig`
`ModuleNotFoundError: No module named 'matminer.figrecipes'`

OR

`from figrecipes import PlotlyFig`
`ModuleNotFoundError: No module named 'figrecipes'`

** matminer (0.7.2)
** plotly (4.14.3)

**Comment by ardunn** [comment]
Have you installed figrecipes? 


https://github.com/hackingmaterials/figrecipes


You can install it by cloning the repository and then `pip install -e .` inside the figrecipes folder (where `setup.py` is)

then you should be able to import it
