### ISSUE TITLE
Can the figrecipe examples be ported to notebooks?

### ISSUE THREAD

**Issue by WardLT** [hackingmaterials/matminer_examples#7]
I think it would be nice to have these as notebooks. Users would be able to see the figures rendered here on GitHub. Plus, iteratively tweaking figures seems is much faster in notebooks (at least for me) and I'd like to advocate their use here. 

What is your take on porting these examples to notebooks?

**Comment by ardunn** [comment]
I agree, but I think #6 already takes care of this. I haven't looked through exactly what @montoyjh put in the visualization notebook, but from the description it seems *most* of the examples we created should be in there. As requested by @computron, the images are also static jpg/png files in /figrecipes

I am also considering making a notebook (or prepending some code to the current visualization nb) specifically as a starter tutorial for figrecipes. Right now what we have is a bunch of examples for each plot type (+formatting) with varying complexity. @WardLT if you are learning figrecipes at the moment, let me know if you think the current examples are insufficient and a 'starter' tutorial notebook is needed.

**Comment by WardLT** [comment]
Sorry, I didn't notice #6. Yea, this sounds like it fixes out problem.

Sure, I'll take a look at the current examples and let you know if there is anything I find confusing about them.

Thanks!

**Comment by ardunn** [comment]
Ok. Now that I've looked over the notebook it seems joey included a subset of the examples in the py files, which I think is good bc. we don't want the notebook to be super long. I think Joey included a good subset of the full set of examples, which gives a nice overview with materials data. For a full list of the examples though, definitely go thru the .py files!

**Comment by montoyjh** [comment]
My strategy was just to include everything that ran without needing API credentials or external datasets, and to add `mode=notebook`.  I did this mainly so the test could run without needing API credentials, but I could also put everything else in an "advanced visualization" notebook that has a separate test requiring API credentials, and we could also include the formatting examples there.

**Comment by ardunn** [comment]
@montoyjh having an advanced visualization notebook is fine by me! The examples I include in the formatting example are more advanced and require Plotly credentials, so that would be very fitting.
